kafka:
  group-id: test-group
  key:
    testKey: test-key
  topic:
    testTopic: test-topic
  address: localhost:9092



spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.kafka.model.KafkaMessage

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.kafka.model.KafkaMessage